### ISSUE TITLE
Update branching strategy

### ISSUE THREAD

**Issue by tackley** [brave/brave-talk#46]
In order to cater for both short and longer lived feature development (especially those that require review), update the branching strategy to support this, following the pattern established by 

`prod` => releases to [talk.brave.com](http://talk.brave.com) (production)
`main` => releases to staging
`dev` => releases to development

1. production releases should only be made after we have been able to test exactly what we're going to release on stage. So these should always be a PR from `main` to `prod` that's basically "make production === stage". These are the only PRs that should go to `prod`.
2. therefore a merge to `main` should only happen when we think the feature is ready to release.
3. when starting a piece of work, create a branch off `main` and keep adding commits there until it's ready to release.
4. to test the code in a real environment, either:
    a.  merge that branch to `dev` - but don't delete the feature branch. Repeatedly merge the feature that feature branch to `dev` as work progresses. Merges to `dev` do not require PRs.
    b. manually initiate the "Deploy to Development" github action selecting that branch - this will deploy just those changes to development. 
5. In-development QA of this feature should happen on dev. 
6. when it's good to go merge the feature branch to `main` - with a PR and security review if required. Do not merge until all reviews are completed.
7. then, after checking on the staging environment (including QA regression testing if needed) PR a production release as per step 1.
8. now and again we will reset `dev` to match `main` just to keep the history tidy.

## Tasks to implement

- [x] create a `prod` branch matching current main
- [x] create a `dev` branch matching current development
- [x] update readme and github action scripts
- [x] update branch protections accordingly
- [x] delete `development` and `staging` branches
